name: "Autosend"

on:
  push: 
    branches: main
  schedule: 
    - cron: 25 09 * * * # 每天9点25分自动执行
  workflow_dispatch:
    inputs:

env:
  TZ: Asia/Shanghai

jobs:
  autosend:
    runs-on: ubuntu-latest
    name: notify

    environment: 
      name: GM_BOT
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: do notification as bot
        uses: nhomble/groupme-notify-action@v1.2
        id: bot
        with:
          bot: ${{ secrets.GM_BOT_ID }}
          message: "Never say die! keepGV forever!"
          token: ${{ secrets.GM_API_KEY }}
      - name: Send Telegram notification
        if: always()
        run: |
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          message="当前时间：$current_time \n GV保号脚本运行完毕！\n 脚本运行结果: ${{ job.status }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$message"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 6
